### ISSUE TITLE
Support installation via Carthage

### ISSUE THREAD

**Issue by nicholaswyoung** [davidstump/SwiftPhoenixClient#10]
[Carthage](https://github.com/Carthage/Carthage) is a simplified dependency manager for iOS/OS-X. I know that you already have a Podspec (which I plan on using for now) but Carthage might be another great place to publish the client... and hopefully, allow you to do so with minimal hassle.

**Comment by mudphone** [comment]
I'd like to take a look at this when I get time. But, if someone else gets to it before me, I won't complain :)

**Comment by nicholaswyoung** [comment]
@mudphone @davidstump Here are the main requirements for adding a package to Carthage. https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

I wonder if @chrismccord would favor adding this package to the PhoenixFramework org, so the Carthage URI would be solid for all time? (Or close to it, anyway.)

**Comment by jonsteinmetz** [comment]
I would also request the option to install via git submodules. But since that should come along for the ride with Carthage support I will just leave that as a comment here. Thanks.

**Comment by jonsteinmetz** [comment]
I would also request the option to install via git submodules. But since that should come along for the ride with Carthage support I will just leave that as a comment here. Thanks.

**Comment by davidstump** [comment]
Finally got some help doing some significant (and much needed) restructuring and the carthage build command succeeds. Please feel free to open other specific issues if you have any trouble with Carthage. Cheers!
