### ISSUE TITLE
Can't keep connection up, seemingly different errors every now and then

### ISSUE THREAD

**Issue by simpers** [davidstump/SwiftPhoenixClient#105]
Connections dies at random times after initially connecting, most often with the error right here. If I try to reconnect, it does not do anything and usually end up with a new error (will edit and update once I get it the next time).

I have a separate WebSocket connection also using StarScream that is connected to another server, and it seems to be running fine, so I suppose the error could be in this layer (SwiftPhoenixClient) and not below.

This however, when connected to either my local phoenix app or the remote deployed one keeps disconnecting and it takes a reboot of the app to get it up again. I'll dump more data as I get it.

```
EventManager.121: Socket log string: SwiftPhoenixClient: transport, Connected to ws://192.168.127.92:4000/events/websocket?token=Bearer%20THIS%20IS%20A%20TOKEN&terminal=951654322
EventManager.121: Socket log string: SwiftPhoenixClient: push, Sending {"event":"phx_join","topic":"terminal:123123123123","payload":{"status":"joining"},"ref":"1","join_ref":"1"}
EventManager.121: Socket log string: SwiftPhoenixClient: push, Sending {"event":"phx_join","topic":"place:123123123123","payload":{"status":"joining"},"ref":"2","join_ref":"2"}
EventManager.110: Connected to the event server.
EventManager.121: Socket log string: SwiftPhoenixClient: receive , {"topic":"terminal:123123123123","ref":"1","payload":{"status":"ok","response":{}},"event":"phx_reply"}
Join channel Optional("terminal:123123123123")
Phoenix reply @ terminal:123123123123: SwiftPhoenixClient.Message
EventManager.121: Socket log string: SwiftPhoenixClient: receive , {"topic":"place:123123123123","ref":"2","payload":{"status":"ok","response":{}},"event":"phx_reply"}
Join channel Optional("place:123123123123")
Phoenix reply @ place:123123123123: SwiftPhoenixClient.Message
EventManager.121: Socket log string: SwiftPhoenixClient: push, Sending {"event":"heartbeat","topic":"phoenix","payload":{},"ref":"3"}
EventManager.121: Socket log string: SwiftPhoenixClient: transport, WSError(type: Starscream.ErrorType.protocolError, message: "", code: 1000)
EventManager.117: Connection error: WSError(type: Starscream.ErrorType.protocolError, message: "", code: 1000)
EventManager.121: Socket log string: SwiftPhoenixClient: channel, error terminal:123123123123
EventManager.121: Socket log string: SwiftPhoenixClient: channel, error place:123123123123
2018-07-16 13:10:01.789333+0200 APP[4346:1817409] SocketStream read error [0x1c4362f40]: 1 54
```

**Comment by dsrees** [comment]
Thanks for reporting @simpers. Let me know if you get any more errors. I'll look into this and see what else I can find.

**Comment by dsrees** [comment]
@simpers Thanks for all of that! My initial thought is that it is server side. The Socket is closing with a 1000 code which means it was closed successfully. However that could also be the case if the client requested it be closed. 

The client should be reattempting a connection if it was closed due to an error. It won't attempt to reconnect if the client or the server closed the connection (at least, that's how it is _supposed_ to work. There may be a bug) Because you're not getting re-connect attempts, my thought is that something is going on here.

If you could, try spinning up the [demo server](https://github.com/chrismccord/phoenix_chat_example) and point your app to that and see if you're still getting disconnects. 

The client is built to work with the latest phoenix version. There currently is not a way to change the configuration to work with different versions of Phoenix.

**Comment by simpers** [comment]
@dsrees I think it might have been this:
   `timeout: 30_000`

I guess depending on the exact timing of this timeout, seeing as the heartbeat also seems to be 30 seconds, that might have caused the `random` disconnects.

I have removed it to see if it helps and it looks promising. However, is there no way to change the  default heartbeat timer of the client?

But how come it is registered as an error? I tried to implement some reconnection logic due to all of this, seeing as it didn't automatically do that even though I set it to (which you answered by saying it doesn't because it's a normal close of the socket), but it fails the reconnect with an actual error. Do I need to create an entirely new socket or something after a successful closure of the socket?

**Comment by dsrees** [comment]
Good find! You can change the heartbeat interval
```
let socket = Socket()
socket. heartbeatIntervalMs = 20000 // 20s heartbeat
```

You can also disable it
```
socket.skipHeartbeat = true
```
See more [here](https://github.com/davidstump/SwiftPhoenixClient/blob/master/Sources/Socket.swift#L21)

I'll have to look into the reconnect logic. There may be something out of place

**Comment by simpers** [comment]
I'll experiment a bit locally with that setting then.

I guess what really confused me and got me pulling my hair was that it was logged as an error and indicated that something was broken, when it in fact as you say was behaving correctly. The only weird thing was that it was recorded as an error so I tried to fix it somehow and started looking in the wrong place.

**Comment by astjohn** [comment]
@simpers - any result on this? I'm seeing similar issues (#122), but only on our staging server... Were you able to resolve it on your end?

**Comment by dsrees** [comment]
@astjohn @simpers Glad you were both able to resolve this by adjusting the server timeout.
