### ISSUE TITLE
SwiftPhoenixClient does not offer a mechanism to configure the underlying `WebSocket` object

### ISSUE THREAD

**Issue by tapi** [davidstump/SwiftPhoenixClient#106]
Currently there is no way to configure the underlying socket. In our case we are interested in setting up  SSL Pinning.

It makes sense that the underlying object would be hidden as you don't want some API consumer to inadvertently change the url or delegate on the underlying connection.

How do you feel about method covers for configurable properties such as the security properties outlined [here](https://github.com/davidstump/SwiftPhoenixClient/blob/master/Example/Pods/Starscream/README.md#self-signed-ssl).

**Comment by dsrees** [comment]
Looks like the link you provided isn't working. If you get that fixed I'll take a look at the outline.

In general, I want to keep the underlying objects hidden, as you mentioned, but am not opposed to exposing some sort of way to build the Socket with configuration.

**Comment by tapi** [comment]
Sorry about that. Should be fixed now. 
FWIW I was just thinking something along the lines of

**Comment by tapi** [comment]
If that approach sounds good to you then I can submit a PR

**Comment by dsrees** [comment]
Yeah i like that. A PR would be great, thanks

**Comment by tapi** [comment]
It looks like theres a soft style preference for 80 char line length in documentation so long as it doesn't affect readability, is my assumption correct?

**Comment by dsrees** [comment]
correct

**Comment by dsrees** [comment]
Released in 0.9.1
