### ISSUE TITLE
Compilation fails when installed with Carthage

### ISSUE THREAD

**Issue by sjmueller** [davidstump/SwiftPhoenixClient#108]
After adding to `Cartfile`
```
github "daltoniam/Starscream"
github "davidstump/SwiftPhoenixClient"
```
Then running `carthage update --platform iOS` and doing a clean build in Xcode:

<img src="https://user-images.githubusercontent.com/29085/44433629-10aabf80-a55c-11e8-8d33-251eb8727b5e.png" width="375" />

The conflict seems to be coming from the `Example` project inside the repo, where the Starscream modulemaps are included:
https://github.com/davidstump/SwiftPhoenixClient/blob/master/Example/Pods/Starscream/zlib/module.modulemap

Manually deleting the `Example` directory from `Carthage/Checkouts/SwiftPhoenixClient` fixes the build error, but unfortunately this must be done with every `carthage update` command.

**Comment by dsrees** [comment]
Thanks for the report. I'll take a look

**Comment by dsrees** [comment]
@sjmueller could you please share your cartfile?
