### ISSUE TITLE
Upload to app store fails

### ISSUE THREAD

**Issue by sjmueller** [davidstump/SwiftPhoenixClient#113]
When installing `SwiftPhoenixClient` with Carthage, uploading to the app store fails with duplicate `Starscream` bundles:

![image](https://user-images.githubusercontent.com/29085/44768580-a0c9a580-ab16-11e8-9734-869622bfb277.png)

**Comment by dsrees** [comment]
@sjmueller thanks for reporting and linking to that other issue. I'll take a look into it

**Comment by dsrees** [comment]
@sjmueller Could you please point your project to the branch `dr/carthage_dupe_issue` and see if that resolves your problem on a clean build? Thanks
