### ISSUE TITLE
How to use with RxSwift

### ISSUE THREAD

**Issue by denis-forti** [davidstump/SwiftPhoenixClient#124]
SwiftPhoenixClient is based on Starscream. There is a great rx-wrapper [https://github.com/RxSwiftCommunity/RxStarscream](url) for Starscream. What do you think, is it possible to use it somehow ?

**Comment by dsrees** [comment]
@denis-forti Currently, no there is no Rx way of using this client. I would love to make an RxSwift wrapper around this client. Glad to see there is some interest if I pursued building this. Maybe I'll start tinkering with it

Thanks for the idea!

**Comment by denis-forti** [comment]
Ok, thank you for answer.
