### ISSUE TITLE
Create a new 0.2.0 release tag, so we an push to CocoaPods

### ISSUE THREAD

**Issue by mudphone** [davidstump/SwiftPhoenixClient#13]
I think we have an old (unnecessary) release tag for 0.2.0. Can you create a new one so that we can push to CocoaPods?

I'm assuming that you have to create the release tags, since I don't think that they come across in my pull requests. Once the tag is created, I can push to CocoaPods (test out my ability to do so), if you'd like.

FYI: I'm preparing to create a Swift 2.0 branch, to support tvOS. I tried to use the existing code with a tvOS app and it barfed on syntax changes. So, I'd just like to wrap up the current version (as a pod release) before starting on Swift 2.0 things.

**Comment by davidstump** [comment]
A new 0.2 tag should be all set. Let me know if you have any trouble pushing to CocoaPods. Also - awesome that you are playing with this and tvOS :D

Thanks!

**Comment by mudphone** [comment]
Okay, it looks like the CocoaPod linter cares about the versions being different 0.2.0 (in the pod spec) and 0.2 (for the tag). I'll open a PR for that small change in the pod spec. I did it locally, and the pod passed the linter. After the PR goes in, I'll push the pod to CocoaPods trunk.

Thanks!

**Comment by davidstump** [comment]
Makes sense. I pulled in the small change so hopefully you are good to go.
