### ISSUE TITLE
Carthage Starscream 3.0.1 Swift 5

### ISSUE THREAD

**Issue by DmitryPR** [davidstump/SwiftPhoenixClient#131]
Hello, Starscream  3.0.1 dependency uses Swift 5.0 but most projects are still using Swift 4.2 

Could you fix the version in Cartfile as 3.0?

error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Starscream')

Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Starscream')

** ARCHIVE FAILED **

**Comment by dsrees** [comment]
Sure thing. I'm planning on a release sometime this week so i'll be sure it's included in that

**Comment by dsrees** [comment]
will be available in 1.0 release
