### ISSUE TITLE
WWDC 19 Native websocket announcement

### ISSUE THREAD

**Issue by sjmueller** [davidstump/SwiftPhoenixClient#140]
With native websockets being announced during “Advances in Networking”, it looks like Starscream is retiring: https://github.com/daltoniam/Starscream/pull/653#issuecomment-499738690

Any plans to switch SwiftPhoenixClient to the new native implementation?

**Comment by dsrees** [comment]
I still need to do some research into this. Reading that comment looks like Starscream may still stick around based on backwards compatibility.

Ideally i would like make the client configurable so you can use any websocket implementation you would like.

**Comment by sjmueller** [comment]
I have built a custom version of SwiftPhoenixClient that uses `URLSessionWebSocketTask` instead of Starscream, lmk if the code is of interest.

**Comment by dsrees** [comment]
If you want to share it, then I'd be interested in taking a look

**Comment by artfulhippo** [comment]
> I have built a custom version of SwiftPhoenixClient that uses `URLSessionWebSocketTask` instead of Starscream, lmk if the code is of interest.

Yes, please share this code

**Comment by dsrees** [comment]
2.x is released which supports URLSessionWebsocketTask for clients targeting iOS >= 13
