### ISSUE TITLE
minimum iOS target must be '9.0' is a Deal Breaker for my app.

### ISSUE THREAD

**Issue by linovate** [davidstump/SwiftPhoenixClient#157]
I have an existing iOS app with quite a few newer features/framework from iOS 10 and iOS 11, which requires me to set minimum iOS target to 11.0 (or higher).  I would love to add chat feature using SwiftPhoenixClient but can't do that simply because my minimum iOS target has to be higher than 9.0.   Rewriting those iOS 10 and 11 features with the equivalent of iOS 9 or older takes too much time and labor, and it doesn't feel right (as it feels like downgrading the app and brings the app backwards).

I like this framework a lot as it allows adding chat feature in a very simple and elegant way, it's such a pity that I can't use it simply because minimum iOS target requirement. I was wondering what's the reason/rationale behind this requirement ?  is it possible to update the framework to remove this requirement completely (or at least bring the minimum iOS target requirement to 11.0 or higher)?  Or is there any workaround? 

Thanks and looking forward to your help on this !

**Comment by dsrees** [comment]
Is xcode giving you an error? If the minimum is iOS 9 and you're targeting 11, everything should work just fine. An issue would arise if you were targeting iOS 8 for example and this library required you to target 9.

**Comment by linovate** [comment]
Yes, Xcode gives me errors:

self.lobbyChannel = channel  // ERROR: Cannot assign value of type 'Channel' to type 'Channel?'

self.lobbyChannel
            .join()
            .delegateReceive("ok", to: self) { (self, _) in
                
                self.navigationItem.title = "[anonymous entered]"
                print("[anonymous entered]")
                self.addText("Joined Channel")
                
            }.delegateReceive("error", to: self) { (self, message) in
                self.addText("Failed to join channel: \(message.payload)")
        }  // ERROR: Value of type 'Channel?' has no member 'join'

Any idea why am I getting these error?

**Comment by dsrees** [comment]
```
pod 'SwiftPhoenixClient', '1.0.1' 
```

Is correct if you are running Swift 4.x. 

Your error has nothing to do with the minimum version of Swift, but instead that you are assigning `channel` which is of _optional_ type `Channel?` to `self.lobbyChannel` which appears to be of _non-optional_ type `Channel`. I don't know where `channel` is coming from but changing `self.lobbyChannel` to

```Swift
var lobbyChannel: Channel?
```

and then calling 
```Swift
self.lobbyChannel?.join()
```

should clear up your error
