### ISSUE TITLE
is there a integration for this and apollo-ios?

### ISSUE THREAD

**Issue by cultofmetatron** [davidstump/SwiftPhoenixClient#158]
currently, I have a subscription endpoint working in web but I need to access it via ios. as I understand it, there needs to be a transport layer adapter between apollo-ios and swiftphoenixclient. is there currently an adapter existing to do this?

**Comment by dsrees** [comment]
I haven't used apollo much so I can't say I'm familiar with the problem that you are looking to solve. But no, there is no adapter. If you could provide more information on what you're trying to do or maybe documentation somewhere, then i might be able to help figure out a solution?
