### ISSUE TITLE
Callbacks on a different queue

### ISSUE THREAD

**Issue by eoinoconnell** [davidstump/SwiftPhoenixClient#159]
Hi, I'm looking to set the callbackQueue on the underlying WebSocket from starscream. I think the best solution would be to make the init for Socket.swift to be public, I can then set my own transport and init my own WebSocket and set the fields I like. 

I can send off a PR if you like, or if you have any better existing solution that would be great

**Comment by dsrees** [comment]
This is something ive been meaning to add to the project. Ideally you should be able to use _any_ websocket liobrary you would like, configured in any way you'd like. I think your PR is a good quick fix but let me take a little bit of a deeper look into this.

**Comment by eoinoconnell** [comment]
Yeah no problem at all, I'm using my fork for now. Enjoy presidents day

**Comment by dsrees** [comment]
Resolved in v1.3.0
