### ISSUE TITLE
Configure client to be compatible with v2_json_serializer.ex

### ISSUE THREAD

**Issue by richard-ash** [davidstump/SwiftPhoenixClient#163]
Is there a way to configure `Socket` to be compatible with the [Phoenix v2 json serializer](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/serializers/v2_json_serializer.ex)?

Seems like the diff between v1 & v2 is that v2 uses arrays to encode the message instead of a dictionary, but seems like `Socket` will always send a dictionary

**Comment by dsrees** [comment]
You can override the `encode` and `decode` closures of the `Socket` to provide custom behavior

https://github.com/davidstump/SwiftPhoenixClient/blob/master/Sources/Socket.swift#L86

```
let socket = Socket(...)
socket.encode = { jsonDictionary in
  // convert json dictionary to array data
}

socket.decode = { jsonData in
  // convert array data to json dictionary
}
```

**Comment by richard-ash** [comment]
Awesome thanks! 😄
