### ISSUE TITLE
Inconsistent dependency between podspec and Cartfile

### ISSUE THREAD

**Issue by peteranny** [davidstump/SwiftPhoenixClient#172]
Just found different dependent versions in podspec and Cartfile

https://github.com/davidstump/SwiftPhoenixClient/blob/master/SwiftPhoenixClient.podspec#L43
```
s.dependency 'Starscream', '~> 3.1.0'
```

https://github.com/davidstump/SwiftPhoenixClient/blob/master/Cartfile#L1
```
github "daltoniam/Starscream" == 3.1.0
```

Should they be consistent?

**Comment by dsrees** [comment]
see #168 

Looks like there is a version 3.1.1 which it could be pinned to
