### ISSUE TITLE
Support iOS 13 min

### ISSUE THREAD

**Issue by jonesrajee** [davidstump/SwiftPhoenixClient#178]
Is there a way to get this to work with iOS 13 as the min target? 

Starscream currently has deprecations for iOS 13, and I can not get this library to work 

https://github.com/daltoniam/Starscream/issues/857
https://github.com/daltoniam/Starscream/issues/868

**Comment by dsrees** [comment]
I don't see an issue here? I was able to create an xcode project, target iOS 13, add the library and create a socket without any warnings. Can you be more clear in what issue you're having?

**Comment by dsrees** [comment]
If you want to try targeting the `2.x` branch as your dependency, then you can do that. It supports URLSession's websocket by default which has a minimum of iOS 13.

**Comment by jonesrajee** [comment]
`You can install SwiftPhoenix Client via CocoaPods by adding the following to your Podfile. Keep in mind that in order to use Swift Phoenix Client, the minimum iOS target must be '9.0'`

**Comment by jonesrajee** [comment]
@dsrees when do you expect the `2.x` branch to release?

**Comment by dsrees** [comment]
That sentence is worded poorly. You can target any iOS version >= 9.0. SwiftPhoenixClient does not require you set your minimum to 9.0, it requires that you don't set it to anything prior to 9.0, such as 8.x (which at this point, basically no one is using)

Are you actually having any warnings or errors in Xcode when attempting to intall SwiftPhoenixClient?

**Comment by jonesrajee** [comment]
@dsrees Yes, your master branch does not work if the minimum target is iOS 13 which you advised to use the unreleased 2.x branch. 

If I use that branch, via Cocoapods or SPM, it’s not working because of the error I mentioned here:

https://github.com/davidstump/SwiftPhoenixClient/issues/178#issuecomment-813588260


My question is; when should we expect the 2.x branch to be released and supported so that projects that target iOS 13 as a minimum version can use this framework?

**Comment by dsrees** [comment]
are you using SwiftPhoenixClient in an app or are you using it as a dependency for another library?

**Comment by jonesrajee** [comment]
> are you using SwiftPhoenixClient in an app or are you using it as a dependency for another library?

Yes, I am trying to use it as a dependency for a internal framework

**Comment by dsrees** [comment]
The 2.x branch does not support library evolution yet. I dont know if RxSwift or Starscream do either. If they do not, then I cannot either.

There's nothing I can change currently until I verify this more.

**Comment by jonesrajee** [comment]
Going to close this as I wait for 2.x release

I reformatted my .framework into a Swift Package which has a dependency on this repo. This allowed me to pull it into my apps without the library evolution issue and iOS 13 is working on this branch.

(I cant figure out why my server handshake won't work without using StarscreamsTransport but ill figure that out another time)
