### ISSUE TITLE
How to save the response from the events in JSON?

### ISSUE THREAD

**Issue by srikanth-chetu** [davidstump/SwiftPhoenixClient#189]
Hi Team,

1) When i am trying to save the presence list in one variable it saving as raw data and it is not coming in JSON format. How can save the data in JSON format?.

2) How can I initiate the "call" event, while initiating, I am getting phx_error response from socket.

Could you please any sample application related to the Call feature. Thanks in advance

**Comment by dsrees** [comment]
@srikanth-chetu could you please provide a short code sample of what you have implemented? That would help provide some context. thanks
