### ISSUE TITLE
Move out additional Rx and Starscream solutions to separate Swift Packages

### ISSUE THREAD

**Issue by thehavre** [davidstump/SwiftPhoenixClient#207]
`SwiftPhoenixClient` may work completely independently using native Apple frameworks. Nowadays it's not necessary to depend it on `RxSwift` additional features and `Starscream` additional implementation.

Unfortunately, `SwiftPhoenixClient` Swift Package requires these dependencies to be installed:

```
dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/ReactiveX/RxSwift.git", .upToNextMajor(from: "5.0.0")),
        .package(url: "https://github.com/daltoniam/Starscream.git", .upToNextMinor(from: "3.1.0")),
    ]
```

This breaks power of its independence and may leads to SPM dependencies incompatibility issue.
One of my projects has it's own `RxSwift` dependency with own version rule (>= 6.0.0). So when I try to add `SwiftPhoenixClient` via SPM it fails, because of Package Resolution issue

```
Dependencies could not be resolved because root depends on 'SwiftPhoenixClient' 3.0.0.
'SwiftPhoenixClient' >= 2.0.0 cannot be used because 'SwiftPhoenixClient' >= 2.0.0 depends on 'RxSwift' 5.0.0..<6.0.0 and root depends on 'RxSwift' 6.2.0.
```

The sad part is that I don't even use `RxSwift` functionality for `SwiftPhoenixClient`.
If it's possible to move out additional dependencies and ship `SwiftPhoenixClient` as an independent package - it would be awesome!

Thanks in advance!

**Comment by dsrees** [comment]
This is definitely the intention of how the project is set up. If it's not working this way then I may have a configuration issue in the Package.swift file

**Comment by dsrees** [comment]
@thehavre could you please change your Package.swift to use the `fix-package-targets` branch and verify it is working for you? Thanks

**Comment by thehavre** [comment]
@dsrees  unfortunately, it won't work , cause you have declared `Rx` and `Starscream` dependencies in one unified `Package.swift`

```
dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/ReactiveX/RxSwift.git", .upToNextMajor(from: "5.0.0")),
        .package(url: "https://github.com/daltoniam/Starscream.git", .upToNextMinor(from: "3.1.0")),
    ]
```

It means that you have declared your Product `SwiftPhoenixClient` with required Product dependencies. My issue arrises when I try to add `SwiftPhoenixClient` to the **Project** (not target). Xcode tries to resolve all **Project's** Packages and finds that it has explicit Package with `RxSwift` Product dependency and also it has `SwiftPhoenixClient` Product with dependencies where `RxSwift` version conflicts with already explicitly added `RxSwift` dependency.

That's why initially I've asked you to divide `Rx` and `Starscream` functionality to separate Packages (not targets), where each package depends on `SwiftPhoenixClient` package. Unfortunately, targets separation in the product can't resolve this issue :(

I don't know if it's possible to do so to not break existing users support, but if it is, it would be great to do so :)

**Comment by dsrees** [comment]
Hmm.. I was using [Moya](https://github.com/Moya/Moya/blob/master/Package.swift) as an example here, assuming that if you used SPM to use Moya, they wouldn't pull non-used dependencies

I need to update to RxSwift 6.0 anyways so would that solve your problem for now until something else if figured out?

**Comment by thehavre** [comment]
Yeah, updating RxSwift works for me. Thanks 🙃

**Comment by dsrees** [comment]
4.0.0 is released which includes RxSwift 6.x

**Comment by JetForMe** [comment]
So, SwiftPhoenixClient still depends on RxSwift and Starscream, and so still pulls them down. May I suggest breaking out the Rx and Starscream support into separate packages that can be included independently?

**Comment by thehavre** [comment]
> So, SwiftPhoenixClient still depends on RxSwift and Starscream, and so still pulls them down. May I suggest breaking out the Rx and Starscream support into separate packages that can be included independently?

It would be perfect and right way to solve any related issue. Updating Rx version was like a half-measurement to solve a consequences :(

**Comment by dsrees** [comment]
@thehavre @JetForMe version 5.0.0 has removed RxSwift and Starscream as dependencies. These extensions will be available in separate repositories
