### ISSUE TITLE
"Invalid HTTP upgrade"

### ISSUE THREAD

**Issue by jeandavid** [davidstump/SwiftPhoenixClient#21]
Hey, 

I am testing the iOS client with the phoenix chat example. Everything works fine locally. When I deploy to heroku, I can't connect through web socket via the iOS client ( js client works fine). I get this error: 
socket closed: Optional("Invalid HTTP upgrade"). 
Can you help me understanding what's wrong? and how to fix it? 

Thanks!

**Comment by chrismccord** [comment]
For native clients, make sure you have `check_origin: false` in your endpoint configuration. Likely you have the default check_origin setting, which enforces the websocket client's origin header to match the server's host. For native apps, there is no origin, so you can set it to false.

**Comment by jeandavid** [comment]
That didn't help. Here's my endpoint configuration:  
config :chat, Chat.Endpoint,
	http: [port: {:system, "PORT"}],
	url: [scheme: "https", host: "enigmatic-hamlet-2977.herokuapp.com", port: 443],
	force_ssl: [rewrite_on: [:x_forwarded_proto]],
	cache_static_manifest: "priv/static/manifest.json",
	secret_key_base: System.get_env("SECRET_KEY_BASE"),
	check_origin: false

On the iOS side, I am just trying to open a socket with:
Phoenix.Socket(domainAndPort: "enigmatic-hamlet-2977.herokuapp.com", path: "socket", transport: "web socket"). 

Any more guidance? Thanks in advance Chris!

**Comment by jeandavid** [comment]
Actually there's another argument to Phoenix.Socket: 
Phoenix.Socket(domainAndPort: "enigmatic-hamlet-2977.herokuapp.com", path: "socket", transport: "websocket", prot: "https").
Now it's working :)

**Comment by davidstump** [comment]
Glad you got it sorted out. I added a snippet to the README about `prot` for clarification :)
