### ISSUE TITLE
How to configure heartbeat?

### ISSUE THREAD

**Issue by jsmestad** [davidstump/SwiftPhoenixClient#213]
@davidstump @dsrees thanks for the library. This may be a foolish question, but how do you configure the heartbeat? I am setting `socket.heartbeatInterval = 1000` but it does not appear to do anything in practice. Reading through the code, I cannot see where `socket.heartbeatTimer` is getting initialized. The only place I can find the heartbeat being set is in `resetHeartbeat()`. I have to be missing it, could you point me in the right direction?

**Comment by dsrees** [comment]
@jsmestad thanks for the question. Are you just trying to change the frequency of the heartbeat?

**Comment by jsmestad** [comment]
I am getting a bunch of `phx_close` events from the client to the server, so in an effort to debug I started to look to see if Heartbeat was even getting sent from the connection. As I started tracing through the Socket initialize methods, I cannot find a test or any code that makes me think the heartbeat timer ever starts.

I must be totally missing it... 🙃

**Comment by dsrees** [comment]
The heartbeat timer gets recreated [once the connection has been opened](https://github.com/davidstump/SwiftPhoenixClient/blob/master/Sources/SwiftPhoenixClient/Socket.swift#L572) using the `heartbeatInterval`. If you're changing that interval after the connection is opened then it won't affect the heartbeat.

Which client version are you using?

**Comment by jsmestad** [comment]
@dsrees ah there it is! I was going crazy thinking it had to exist.

I am using `master` at the moment
