### ISSUE TITLE
socket closed: Optional("connection closed by server")

### ISSUE THREAD

**Issue by turnabout4** [davidstump/SwiftPhoenixClient#22]
Hi, thanks for awesome pod!
I tried socket.join and send message.
but, 40sec after joining, connection closed automatically.
```
(10sec later)socket message: {"topic":"phoenix","ref":null,"payload":{},"event":"heartbeat"}
(20sec later)socket message: {"topic":"phoenix","ref":null,"payload":{},"event":"heartbeat"}
(40sec later)socket closed: Optional("connection closed by server")
```

so I added timeout value to  ```phoenix_server/web/channels/user_socket.ex```
```
defmodule PhoenixServer.UserSocket do
  use Phoenix.Socket

  ## Channels
  channel "rooms:*", PhoenixServer.RoomChannel

  ## Transports
  transport :websocket, Phoenix.Transports.WebSocket,
    timeout: :infinity

  def connect(_params, socket) do
    {:ok, socket}
  end

  def id(_socket), do: nil
end
```
but, it doesn't work...

What should I do to keep socket connection?

**Comment by davidstump** [comment]
Can you give me some extra info (versions, etc)? 

I just pulled the most recent version of the Phoenix Chat Example code as well as the current pod release for this client and all seems functional on a vanilla test.

Thanks!

**Comment by turnabout4** [comment]
Thanks for rapid response!

Certainly, the problem didn't occur in the most recent version of the Phoenix Chat Example code!

but , I'm using project generated by  ``` mix phoenix.new testChat ```.

phoenix version is 1.0.3(latest)

```
  defp deps do
    [{:phoenix, "~> 1.0.3"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"}]
  end
```

and then, I edited only 2 files.

1.add one line to ``` testChat/web/channels/user_socket.ex```
```
# added  this code
transport :longpoll, Phoenix.Transports.LongPoll
```

2. add new file ```testChat/web/channels/room_channel.ex```

```
defmodule TestChat.RoomChannel do
  use Phoenix.Channel
  require Logger

  def join("rooms:lobby", message, socket) do
    Process.flag(:trap_exit, true)
    :timer.send_interval(5000, :ping)
    send(self, {:after_join, message})
    {:ok, socket}
  end

  def join("rooms:" <> _private_subtopic, _message, _socket) do
    {:error, %{reason: "unauthorized"}}
  end

  def handle_info({:after_join, msg}, socket) do
    broadcast! socket, "user:entered", %{user: msg["user"]}
    push socket, "join", %{status: "connected"}
    {:noreply, socket}
  end

  def handle_info(:ping, socket) do
    push socket, "new:msg", %{user: "SYSTEM", body: "ping"}
    {:noreply, socket}
  end

  def terminate(reason, _socket) do
    Logger.debug"> leave #{inspect reason}"
    :ok
  end

  def handle_in("new:msg", msg, socket) do
    broadcast! socket, "new:msg", %{user: msg["user"], body: msg["body"]}
    {:reply, {:ok, %{msg: msg["body"]}}, assign(socket, :user, msg["user"])}
  end
end
```

server_console 

```
Generated testChat app
[info] Running TestChat.Endpoint with Cowboy on http://localhost:4000
23 Nov 07:10:48 - info: compiled 5 files into 2 files, copied 3 in 1031ms
[info] JOIN rooms:lobby to TestChat.RoomChannel
  Transport:  Phoenix.Transports.WebSocket
  Parameters: %{"body" => "joining", "subject" => "status"}
[info] Replied rooms:lobby :ok
[debug] > leave :shutdown
```

ios_console

```

<_TtCV18SwiftPhoenixClient7Phoenix7Message: 0x7fa0624d40d0>
socket message: {"topic":"phoenix","ref":null,"payload":{},"event":"heartbeat"}
socket message: {"topic":"rooms:lobby","ref":null,"payload":{"user":"SYSTEM","body":"ping"},"event":"new:msg"}
<_TtCV18SwiftPhoenixClient7Phoenix7Message: 0x7fa06258a310>
socket message: {"topic":"rooms:lobby","ref":null,"payload":{"user":"SYSTEM","body":"ping"},"event":"new:msg"}
<_TtCV18SwiftPhoenixClient7Phoenix7Message: 0x7fa0624d40d0>
socket message: {"topic":"rooms:lobby","ref":null,"payload":{"user":"SYSTEM","body":"ping"},"event":"new:msg"}
<_TtCV18SwiftPhoenixClient7Phoenix7Message: 0x7fa06258b450>
socket message: {"topic":"rooms:lobby","ref":null,"payload":{"user":"SYSTEM","body":"ping"},"event":"new:msg"}
<_TtCV18SwiftPhoenixClient7Phoenix7Message: 0x7fa06258a240>
socket message: {"topic":"rooms:lobby","ref":null,"payload":{"user":"SYSTEM","body":"ping"},"event":"new:msg"}
<_TtCV18SwiftPhoenixClient7Phoenix7Message: 0x7fa06258afb0>
socket message: {"topic":"rooms:lobby","ref":null,"payload":{"user":"SYSTEM","body":"ping"},"event":"new:msg"}
<_TtCV18SwiftPhoenixClient7Phoenix7Message: 0x7fa064385490>
socket closed: Optional("connection closed by server")
```

**Comment by col** [comment]
I just had the same issue. I have not fully looked into this yet but I think Phoenix has added heartbeats. If the server doesn't receive a heartbeat every x seconds it'll close the connection. 
This should really be fixed in the library but you can easily work around this to your own app with something like this:

```swift
NSTimer.scheduledTimerWithTimeInterval(10, target: self, selector: "sendHeartbeat", userInfo: nil, repeats: true)
...
func sendHeartbeat() {
        self.socket.send(Phoenix.Payload(topic: "phoenix", event: "heartbeat", message: Phoenix.Message(message: [String: AnyObject]())))
    }
```

**Comment by chrismccord** [comment]
Yes the client needs to heartbeat, as configured by the window on the server. (timeout is default set to 2x heartbeat, so 60s on the server). The client should be by default heartbeating every 30s.

**Comment by PoCk3T** [comment]
@col any idea how to translate that for Android ?
I can only put Enveloope objects as unique parameter of socket.push(), and here is what I tried & failed, leading to timeouts :

_socket.push(new Envelope("phoenix", "heartbeat", null, "heartbeat"));_

With Envelope defined respectively with a topic, an event, a Payload and a ref.

Any idea ?

**Comment by col** [comment]
@PoCk3T - Are you calling `socket.push(new Envelope("phoenix", "heartbeat", null, "heartbeat"));` every 30 seconds?

If that's not your issue, you could try sending a payload other than null. My example workaround was at least sending a payload with an empty message property.

**Comment by davidstump** [comment]
Sorry for the delay - added a heartbeat every 30s from the iOS device to phoenix with the message Pong (for now). This is currently on master but will push it up with the next minor version with some other tweaks. I'll close this for now.
