### ISSUE TITLE
SSL Pinning support after StarScream removal

### ISSUE THREAD

**Issue by udaypatial** [davidstump/SwiftPhoenixClient#228]
Hey how can I add `SSLPinning` support, now that `URLSessionWebSocket` is used?

**Comment by udaypatial** [comment]
`URLSessionTransport` is internal and I am unable to override 
`func urlSession(_ session: URLSession,
                           didReceive challenge: URLAuthenticationChallenge`

**Comment by dsrees** [comment]
5.2.2 release changes `URLSessionTransport` to be `open`

```
class CustomTransport: URLSessionTransport {
  // Implement your delegate methods to receive your challange
}

let transport: ((URL) -> PhoenixTransport) = { url in CustomTransport(url: url)}
let socket = Socket(endPoint: "https;//example.com", transport: transport)
```

Let me know if this you still have any issues. Thanks
