### ISSUE TITLE
Crash in `Channel.swift` `off()` function

### ISSUE THREAD

**Issue by udaypatial** [davidstump/SwiftPhoenixClient#235]
Getting this crash intermittently attached the screenshot.
![Screenshot 2023-04-11 at 11 49 12 AM](https://user-images.githubusercontent.com/4548634/231221014-2f3b9e54-abe9-4258-ae88-7b15690c9910.png)

**Comment by dsrees** [comment]
This appears to be the same issue behind #223 as well.

**Comment by dsrees** [comment]
Since its a threading issue, it's pretty hard to pin down exactly but please update to 5.3.0 and let me know if you continue to see this error or not. Thanks!

Closing for now. Please reopen if you're still getting this crash on 5.3.0
