### ISSUE TITLE
Crash in `Socket.append<T>(callback:to:)` function

### ISSUE THREAD

**Issue by msandel6** [davidstump/SwiftPhoenixClient#238]
I'm seeing this crash intermittently when attempting to join a new phoenix topic:
<img width="1037" alt="Screenshot 2023-05-09 at 6 36 09 PM" src="https://github.com/davidstump/SwiftPhoenixClient/assets/42417496/334f4e82-2afe-4216-8154-96d0aeac907e">

**Comment by dsrees** [comment]
Could you provide the whole stack? And what version of the client are you running

**Comment by msandel6** [comment]
I'm running version 5.3.0. Here's the call stack:
<img width="808" alt="Screenshot 2023-05-10 at 10 13 38 AM" src="https://github.com/davidstump/SwiftPhoenixClient/assets/42417496/9911fa8b-3d48-45a0-99e3-e1f13cdb917b">

I did some more investigating this morning, and this crash virtually disappears when I call `Channel.join()` from the main thread (which I'd obviously like to avoid) vs. a background thread. Based on that I'm pretty confident it's a threading issue, but I'll keep looking into it too.

**Comment by msandel6** [comment]
Converting the `stateChangeCallbacks` to a `SynchronousArray` seems to have helped, though I haven't had time to do any extensive testing or look for unwanted side effects yet. I should get around to that later today and could put up a PR with the change if it looks ok and there aren't any concerns from your side @dsrees!

**Comment by msandel6** [comment]
I made a PR [here](https://github.com/davidstump/SwiftPhoenixClient/pull/239). Let me know if you have any questions or concerns, or if there's any important context I'm missing.

**Comment by dsrees** [comment]
should be resolved in 5.3.1. Thanks for your patience, please let me know if something else pops up
