### ISSUE TITLE
Long polling support?

### ISSUE THREAD

**Issue by col** [davidstump/SwiftPhoenixClient#24]
Is Long polling supported? From what I can see the WebSocket implementation is highly coupled with the socket implementation. Do you have any plans to de-couple these and add support for other transport layers?

**Comment by davidstump** [comment]
This implementation mirrored the Phoenix js at the time it was created. I don't have any concrete plans to change the implementation, however, I am always open to further discussion or pull requests showing what people believe to be an improvement. Thanks for asking :)
