### ISSUE TITLE
Automatic success for `Channel.leave()` attempts when offline

### ISSUE THREAD

**Issue by msandel6** [davidstump/SwiftPhoenixClient#241]
### Issue:
This week, I encountered unexpected behavior when a user triggered `join` and `leave` events on various topics while unable to connect to the internet. 

### Cause:
After some investigation, I found that `Channel.leave()` automatically returns a success if `canPush` is false, even though the `phx_leave` event was never pushed and the channel instance was never removed from the socket.

<img width="663" alt="Screenshot 2023-05-12 at 5 04 00 PM" src="https://github.com/davidstump/SwiftPhoenixClient/assets/42417496/d19def15-164b-416b-b477-1fab6185d856">

### Question:
Was there a specific use case for that line to be added (presumably with a different reason for `canPush == false`)? If not, can it be safely removed?

The bug in my app was caused by a local array of joined channels being out of sync with the socket after receiving these "ok" events without a channel ever actually being removed from the socket. [I made a PR](https://github.com/davidstump/SwiftPhoenixClient/pull/240) that will allow clients to access the `Socket`'s list of channels directly, which will resolve my problem for now. That said, an app could listen for successful leave events for reasons other than keeping track of open channels, in which case this "fake" success would still lead to bugs.

**Comment by dsrees** [comment]
This is a behavior in the [phoenix js client](https://github.com/phoenixframework/phoenix/blob/main/assets/js/phoenix/channel.js#L219) that SwiftPhoenixClient is porting. I'm not sure why that behavior was decided upon

**Comment by msandel6** [comment]
> The client assumes that leave will be successful and allows the app the discard the channel 

Is this a safe assumption? If so, then I think [this PR](https://github.com/davidstump/SwiftPhoenixClient/pull/240) should unblock my use case.
