### ISSUE TITLE
Crash on Channel initialization

### ISSUE THREAD

**Issue by udaypatial** [davidstump/SwiftPhoenixClient#247]
Facing a crash on production while trying to initialize a channel. Below's the crash logs if it helps

Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x3a6d70 _swift_release_dealloc + 32
1  libswiftCore.dylib             0x3a8424 bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) + 136
2  SwiftPhoenixClient             0xc08c specialized _ArrayBuffer._consumeAndCreateNew(bufferIsUnique:minimumCapacity:growForAppend:) + 256
3  SwiftPhoenixClient             0xac3c specialized Socket.delegateOnOpen<A>(to:callback:) + 342 (Socket.swift:342)
4  SwiftPhoenixClient             0x7fdc Channel.init(topic:params:socket:) + 136 (Channel.swift:136)
5  SwiftPhoenixClient             0x1dc80 Socket.channel(_:params:) + 112 (Channel.swift:112)
6 MyApp                       0xd03ef8 PhoenixChannel.init(socketConnection:topic:) + 4387372792

**Comment by udaypatial** [comment]
@dsrees Would appreciate any help with this.

**Comment by dsrees** [comment]
should be resolved in 5.3.1. Thanks for your patience, please let me know if something else pops up

**Comment by dsrees** [comment]
Note that this version has not be deployed on cocoapods due to an internal server error on their end. It should be available via SPM however

**Comment by udaypatial** [comment]
Awesome thanks a ton @dsrees .
