### ISSUE TITLE
Leave not public and has wrong event

### ISSUE THREAD

**Issue by sjrmanning** [davidstump/SwiftPhoenixClient#25]
I've avoided creating a pull request for this as I'm hanging out for #17 to get pulled in, and my fork currently conflicts with that as it also fixes the same issue.

The `leave` methods on `Phoenix.Socket` and `Phoenix.Channel` aren't public, and the `leave` method that is there isn't using the right `phx_leave` event in the message. You can see my commit here for the fix: https://github.com/sjrmanning/SwiftPhoenixClient/commit/8f652ad36f9cfd0e374789492f53ae5946813fb5

**Comment by davidstump** [comment]
Sorry for the delay - I pulled in #17 so feel free to push your fixes (if you would like).

Thanks!

**Comment by sjrmanning** [comment]
Cool, just saw that! I'll work on a pull request now. Cheers :)

**Comment by sjrmanning** [comment]
Fixed and merged in from #26
