### ISSUE TITLE
Version 5.3.1 is unavailable via cocoapods

### ISSUE THREAD

**Issue by konstantin-jugl** [davidstump/SwiftPhoenixClient#250]
In official podspec https://cocoapods.org/pods/SwiftPhoenixClient 5.3 is last one.
Updating local repo with 'pod repo update' wasn't helpful as well as 'pod install --repo-update'
it says

None of your spec sources contain a spec satisfying the dependency: `SwiftPhoenixClient (= 5.3.1)`.

**Comment by dsrees** [comment]
just pushed it
