### ISSUE TITLE
What are the payload size limits?

### ISSUE THREAD

**Issue by timetraveler90** [davidstump/SwiftPhoenixClient#254]
As I am not managing to find it anywhere in the doc nor the code I decided to ask here what are the limits for the payload size in kilobytes.

If possible provide me the example where it's set to be like that, please.

Thanks in advance.

**Comment by dsrees** [comment]
Should be whatever the limit of `maximumMessageSize` is in `URLSessionWebSocketTask` which appears to be able a 1MB

https://stackoverflow.com/questions/77669132/what-is-the-default-value-for-maximummessagesize-in-urlsessionwebsockettask

**Comment by timetraveler90** [comment]
Thanks for answering, appreciate it!
