### ISSUE TITLE
Port in Host: HTTP header

### ISSUE THREAD

**Issue by lucacorti** [davidstump/SwiftPhoenixClient#27]
Is there any reason to add the port to the hostname in this Host: header? This seems at least to be incompatible with my haproxy setup.

https://github.com/davidstump/SwiftPhoenixClient/blob/a1c7251b69b5367c09f74556b70396668f482d58/Example/Pods/Starscream/WebSocket.swift

**Comment by lucacorti** [comment]
Sorry, didn't realize this is a bug in StarScream.

**Comment by davidstump** [comment]
No worries. Apologies - I wondered if that was the issue, but had not had time to test yet.

Cheers

On Wed, Feb 17, 2016 at 9:55 AM Luca Corti

<
mailto:Luca Corti <notifications@github.com>
> wrote:

Sorry, didn't realize this is a bug in StarScream.

**Comment by davidstump** [comment]
Hi,
Look at that great stuf I've  just found, I thought  you moight like it as weel as me,  check  this out <http://clemente.ajlconsultingltd.com/lnxj/97>

Good wishes, David Stump
