### ISSUE TITLE
iOS 8

### ISSUE THREAD

**Issue by TigerWolf** [davidstump/SwiftPhoenixClient#28]
Is it possible to make version 2 work with iOS 8 rather than 9 only?

**Comment by davidstump** [comment]
It's been a while since we updated/added the docs for iOS 9, have you tried bumping your plafrorm down to 8? If so, can you give me an idea what kind of errors you are running into?

Thanks for any details!

**Comment by TigerWolf** [comment]
I would need to fork the pod and lower the required version of iOS here:

https://github.com/davidstump/SwiftPhoenixClient/blob/master/SwiftPhoenixClient.podspec#L39

Is there any specific iOS 9 features you are using that require such a high version in order to use the Pod?

**Comment by davidstump** [comment]
The requirement was a PR I believe and I don't remember offhand if they had any specific requirements for iOS 9. Feel free to test and let me know how it goes.

Thanks!

**Comment by Douvi** [comment]
any news ?

**Comment by davidstump** [comment]
Douvi - Unfortunately, I have not had a chance to run tests against iOS 8. Unless you would like to check and report back, I know an alternative client has also been created (Issue #29) if your app requires iOS 8 at this time.

Cheers.
