### ISSUE TITLE
Cannot invoke value of type 'Phoenix.Message.Type' with argument list '(message: [String : Any])' // Is there a way to send up a message with mixed types?

### ISSUE THREAD

**Issue by tslater** [davidstump/SwiftPhoenixClient#30]
I'd like send up json-like data, with arrays, numbers, and strings. When I have all strings as values, I'm able to send a message, but not when I allow the values to be anything. Is it possible currently to do that? In other words, if my message is a [String:String] that works, but not  [String : Any].

**Comment by tslater** [comment]
I figured out how to do it. [String:AnyObject]? instead of [String : Any] or [String : Any?].

**Comment by davidkuhta** [comment]
@tslater Any chance you could share an example of this? I couldn't get mine to work.
