### ISSUE TITLE
onError event

### ISSUE THREAD

**Issue by tslater** [davidstump/SwiftPhoenixClient#31]
I'm new to swift, so I may be misreading the source code on this, but it doesn't look like there is a way to know about an error event? I would really like to be able to listen for errors and respond to error events.

**Comment by davidstump** [comment]
Just pushed this functionality and examples to master. Will push it along with a new minor version update with a few other tweaks.  Thanks!

**Comment by davidstump** [comment]
P.S. This will catch all errors on the iOS side, your Phoenix app would need to broadcast an "error" event up to the websocket to be picked up on this end

```
broadcast! socket, "error", %{body: "Womp"}
```

**Comment by tslater** [comment]
Awesome. Nice work. Thanks!
ᐧ
