### ISSUE TITLE
Update cocoapods

### ISSUE THREAD

**Issue by bbrock25** [davidstump/SwiftPhoenixClient#33]
As I mentioned in #32 there was an issue where the phoenix websocket server was killing the connection after 30 seconds or so. I ran into this issue while running the a project where the dependency was installed via from the cocoapods repo, when running with the dependency locally, I have had no issues. 

If you have the time, could you please update the version hosted on cocoapods to be current with master? 

Thanks!

**Comment by NilsLattek** [comment]
New version on cocoapods would be great! I just noticed that the reconnect interval is still 5000sec in the cocoapods version. The bug is already fixed in master for some time.

**Comment by davidstump** [comment]
The new updates are pushed up as the 0.3 release on CocoaPods.

**Comment by bbrock25** [comment]
Awesome, thanks @davidstump
