### ISSUE TITLE
Channel Presence

### ISSUE THREAD

**Issue by weixiyen** [davidstump/SwiftPhoenixClient#34]
Phoenix 1.2 introduced Presence.

Was wondering if this library will be supporting it.

Thanks!

**Comment by davidstump** [comment]
Absolutely. Once I get this next minor version bump pushed up to Cocoapods, thats next up on my list :)

**Comment by tony612** [comment]
@davidstump Any plan for this feature? Phoenix 1.2 is released 😁

**Comment by davidstump** [comment]
The other small features have been launched and there is a presence branch WIP, but I would love a PR if you have the time.

**Comment by serejahh** [comment]
Any plans?

**Comment by davidstump** [comment]
Now that the project is nicely updated/refactored I just need to find time to implement this. I did a quick test a few weekends ago and getting presence up and running went pretty smooth for a simple test. Welcome all PRs as always.

**Comment by mudphone** [comment]
@davidstump I've started some updates based on your initial swag. I'd love to get feedback on style, approach, etc. I'm going over the JS Phoenix Presence client code and doing a port, as it appears was @davidstump's initial cut.  It's over on a branch here: https://github.com/mudphone/SwiftPhoenixClient/commit/91e8094aba6dc017a7c4926a83c07542eaa3b353

**Comment by davidstump** [comment]
@mudphone <3

Looks fantastic! Going through the JS client and porting was indeed my plan.

**Comment by mojidabckuu** [comment]
Hi, @davidstump any updates on presence port?

**Comment by simpers** [comment]
What is the status on this?

We probably need this urgently and so if it isn't already fixed/merged I might take it upon myself tomorrow to get it done. Let me know @davidstump

**Comment by davidstump** [comment]
I'll defer a little to @dsrees as the active maintainer - but I know there is some implementation work done:

https://github.com/davidstump/SwiftPhoenixClient/blob/master/Sources/Presence.swift

If you are going to do any additional work - that might be a good starting point.

Cheers.

**Comment by simpers** [comment]
@davidstump thanks for the quick reply!

I'll see what I can do tomorrow then 👍

**Comment by dsrees** [comment]
@simpers Would love a contribution on this! The Presence class mentioned above by @davidstump hasn't been touched in awhile, though it would be a good place to start. I'll be happy to work with you to get Presence working!

**Comment by dsrees** [comment]
@simpers , I am: @dsrees

I'll also take a look into this

**Comment by dsrees** [comment]
finished in #129. Will be fully supported in 1.x

**Comment by mudphone** [comment]
🔥🔥🔥
