### ISSUE TITLE
Socket error handling

### ISSUE THREAD

**Issue by NilsLattek** [davidstump/SwiftPhoenixClient#35]
There is an event for handling errors on channels, but I think it would also make sense to have something similar on the socket itself. This would allow for a better global error handling (show the user when the connection is offline). It would also be in line with the channel javascript sdk:
https://github.com/phoenixframework/phoenix/blob/master/web/static/js/phoenix.js#L68-L96

What do you think?

**Comment by davidstump** [comment]
The Socket class currently has hooks for onOpen, onError, onClose, etc. (https://github.com/davidstump/SwiftPhoenixClient/blob/master/Pod/Classes/Phoenix.swift#L305-L334), however these are not exposed at the moment. Do you have a thought/preference/etc for how these would be utilized on the ViewController side?

**Comment by NilsLattek** [comment]
It would be great to make these three hooks public and maybe also the isConnected method.
I have two use cases in mind:
* Show the user that the server-connection is open/closed. At the moment I can only do this through a manual heartbeat channel.
* This would also allow me to extend the current sendBuffer cache to also save the unsend messages to disk if the app gets closed. If the socket is closed I could cache every message to ram&disk and resend it when the connection is open again. So for this case the onOpen/onClose hooks would be really helpful.

For my case it would be enough to have just one listener for the onOpen/onClose hooks. But in order to have the same api as the channel and the JS-Api we could use the same ```on("error")``` method from the Channel class and allow multiple listeners.
I hope that was understandable 😄  great work so far!

**Comment by danielrees18** [comment]
Supported in 0.8.0

```Swift
let socket = Socket(url: "ws://localhost:4000/socket/websocket")

socket.onOpen { print("Socket Opened") }
socket.onClose { print("Socket Closed") }
socket.onError { error in print("Socket Error: ", error.localizedDescription) }

socket.connect()
```
