### ISSUE TITLE
It is not possible to dealloc a socket instance.

### ISSUE THREAD

**Issue by NilsLattek** [davidstump/SwiftPhoenixClient#38]
When I am storing my socket in a property like 
```swift
var socket: Phoenix.Socket?
```
and lets say I want to close the connection when the user performs a logout:
```swift
socket = nil
```
The socket is never deallocated because it has up to three NSTimers which hold a strong reference to the socket. (reconnect, hearbeat, sendBufferTimer).
A solution would be to expose a disconnect method which stops all timers and leaves all channels. The channels hold also a strong reference, which can be solved by #37 or automatically leaving all channels on disconnect.

**Comment by davidstump** [comment]
Issue #39 is talking about a public `leave` function for disconnecting from a socket connection. Any reason not to also stop all timers and make that the recommended way to leave and disconnect?

**Comment by NilsLattek** [comment]
The ```leave``` function is for leaving a channel and not fully closing a socket if I understand this correctly?
At the moment I am using this implementation to fully disconnect the socket from the server: https://github.com/NilsLattek/SwiftPhoenixClient/blob/disconnect/Pod/Classes/Phoenix.swift#L266-L276 
(Use Case scenario: User performs a logout and I want to fully close the connection. Or goes into an offline mode.

**Comment by davidstump** [comment]
Ah yeah - good call. The leave function could be used for an individual channel, but leave other channels open if desired. 

The only potential issue I see is that if we are making a public way to disconnect from the socket, your function does not allow a user to pass a callback like they could with the `close` function by itself. I might be in favor of a solution where `invalidateTimers` is a function that gets called when a public close function is called on Socket.

Thoughts?

**Comment by NilsLattek** [comment]
Yes that sounds good to me. So we would have a new function ```invalidateTimers``` which is private and then make socket ```close``` public and call invalidateTimers inside. Correct?

**Comment by davidstump** [comment]
Just set `close` and `leave` to public and added the `invalidateTimers` function on the most recent commit to master. Will go out with the next release.

Cheers!

**Comment by NilsLattek** [comment]
Awesome, thank you! Just tested the master branch. 👍
