### ISSUE TITLE
leave function on Socket is private

### ISSUE THREAD

**Issue by Anders123fr** [davidstump/SwiftPhoenixClient#39]
I cannot find a way to close a socket connection, other than the method as seen in the ``leave()`` function in the ``Socket`` class:

```
let leavingMessage = Phoenix.Message(subject: "status", body: "leaving")
let payload = Phoenix.Payload(topic: topic, event: "leave", message: leavingMessage)
socket.send(payload)
```

Why not make the ``leave()`` function public in the ``Socket`` class?

**Comment by davidstump** [comment]
Good idea. Would you make it public as is, or allow the user to pass in any of the message/payload?

Would you have time to open a PR?

Thanks for the suggestion!

**Comment by davidstump** [comment]
Also - are you attempting to leave a channel (the `leave` function) or disconnect from the socket entirely? There are two (currently non-public) functions that handle the separate behaviors.

**Comment by Anders123fr** [comment]
I would like to be able to close a channel and a socket. I have a list of chats in my app, and I would like to be able to close a chat channel when the user leaves a chat page. When he enters a new chat, I would like to open a new channel. At the moment, multiple channels are opened at the same time. Also when the user then leaves the page wth a list of the different chats, I would like to close the socket. 

If it doesn't cause any problems, I would suggest making both functions public. 
I am on vacation for the next week, so if you could make the pull request, it would be totally awesome :)

**Comment by davidstump** [comment]
Updated the two methods to public in the most recent commit to master. Will go out with the next release. 

Cheers!

**Comment by Anders123fr** [comment]
That is fantastic. 
Thank you very much!
