### ISSUE TITLE
Better Name?

### ISSUE THREAD

**Issue by davidstump** [davidstump/SwiftPhoenixClient#4]
@mudphone Any thoughts on the repo name? The current name was just a quick filler when I started playing with channels. Thanks :)

**Comment by mudphone** [comment]
[Family Apodidae: several genera and numerous species, including the common Eurasian swift (Apus apus).]

**Comment by mudphone** [comment]
:smile:

**Comment by mudphone** [comment]
Hmmm... Jonathan Swift wrote Gulliver's Travels...

**Comment by mudphone** [comment]
Apparently I'm bad at this naming thing...

**Comment by davidstump** [comment]
Ha - me too. I updated it to SwiftPhoenixClient for the moment.
