### ISSUE TITLE
Enhancement or bridge to Objective-C

### ISSUE THREAD

**Issue by therobinsj** [davidstump/SwiftPhoenixClient#41]
Hey!

I would love to help, just some thoughts;

There's a existing [Objective-C library](https://github.com/RokkinCat/phoenix-objc), I have opened a issue to see if it's still maintained. By the looks of it, I think its abandoned.

I'm still learning Elixir and playing around with Phoenix. I am comfortable in Objective-C and have some experience with Swift. What I can do is, either help out with some of the issues labeled as enhancements or write the bridging header to Objective-C.

Any enhancements that should be prioritised? 

Cheers 😄

**Comment by davidstump** [comment]
Hey Back!

Help would be awesome! 

Any of the enhancements (tests and carthage support) or the Objective-C header would all be a great addition. I would say any of them that spark your interest would be fantastic. 

Thanks!

**Comment by therobinsj** [comment]
Awesome!

Look forward to be working with you 😃
