### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by davidkuhta** [davidstump/SwiftPhoenixClient#44]
Hey there!

Just wanted to have a place to discuss Swift 3 issues.

I've started working on a migration now that Starscream has a branch supporting it. Any chance you could make a new branch here to push to?

Cheers.

**Comment by davidstump** [comment]
Sorry for the delay - time keeps getting away from me. I setup the swift3 branch if you (or anyone else) still has any interest. Thanks for getting the discussion started 👍
