### ISSUE TITLE
leave event should be "phx_leave"

### ISSUE THREAD

**Issue by tony612** [davidstump/SwiftPhoenixClient#45]
This should be `phx_leave`, right? https://github.com/davidstump/SwiftPhoenixClient/blob/49925f12a28dbf65354fa4963b5b49f7f1b0ccce/Pod/Classes/Phoenix.swift#L411
Otherwise, Phoenix won't handle the leave event

**Comment by Anders123fr** [comment]
You are right! 
This is a really important issue, hope that it will be fixed soon.
And it would also be fine to release a new version now with all those commits after version 0.0.3 :)

**Comment by davidstump** [comment]
Thanks for the reminder - pushed this up to master. 👍

**Comment by Anders123fr** [comment]
Thanks for the new release! 
But I think you forgot to set the version in the podspec, so it won't update using CocoaPods :)
