### ISSUE TITLE
CocoaPod version is 0.3 but newest release is 0.4

### ISSUE THREAD

**Issue by Anders123fr** [davidstump/SwiftPhoenixClient#47]
It seems that the newest pod version 0.3, does not point to the newest release which is 0.4
<img width="982" alt="skaermbillede 2016-08-08 11 25 36" src="https://cloud.githubusercontent.com/assets/1019341/17475410/36910a38-5d5b-11e6-9b23-a61f37fc040c.png">

**Comment by BryanJBryce** [comment]
Use Carthage ;)

**Comment by serejahh** [comment]
@davidstump could you push new podspec, please?
