### ISSUE TITLE
Support receive hooks

### ISSUE THREAD

**Issue by NilsLattek** [davidstump/SwiftPhoenixClient#51]
The phoenix js sdk allows to receive the reply to a pushed message:

``` javascript
// from the phoenix.js file
channel.push("new_msg", {body: e.target.val}, 10000)
.receive("ok", (msg) => console.log("created message", msg) )
.receive("error", (reasons) => console.log("create failed", reasons) )
.receive("timeout", () => console.log("Networking issue...") );
```

The `receive("ok")` callback will be called with the response_payload returned in the channel:

``` elixir
def handle_in("ping", payload, socket) do
  response_payload = %{"some_result" => 123}
  {:reply, {:ok, response_payload, socket}
end
```

This allows for an easier message -> reply style of programming when using channels. At the moment we do not have this functionality in the iOS SDK. The implementation in JS just listens for a `phx_reply` event and compares the `ref` ids.
I might look into that issue soon, but I guess it would require a little bit more work or refactoring. Also since it requires parsing json please first have a look at #49.

**Comment by davidstump** [comment]
That definitely looks interesting. 

This SDK was written mirroring the very first Phoenix JS implementation. Since then the PhoenixJS has been improved in a number of different ways (including Presence functionality) that would most likely be good spots for refactoring this code base. On my long wish list for this SDK is to refactor the majority of it following the patterns over the past few years since it was initially created. I just haven’t been able to tackle it yet unfortunately. 

Thanks for starting the conversation.

**Comment by NilsLattek** [comment]
Since you are talking about bigger refactorings, I personally don't like the large Phoenix.swift file with all the nested classes. I would like to see this split into multiple files since it would make the codebase more readable. Maybe we can tackle this once you have more time or I can give a try sometime. But for this I think we should look again into the unittest case. Maybe once Swift 3 and the Swift Package Manager is out and we can ditch cocoapods to make things easier with the project-file. (Just guessing here, since I haven't looked into Swift Packager Manager or Swift 3 yet...)

**Comment by davidstump** [comment]
Agreed about the Phoenix.swift. That was initially done before Cocoapods was setup to allow people to copy down one swift file (or a few swift files) and pull them into their project. If we are going to use the native package manager (good idea) I would also like to break them apart. Better for both readability and testing. 

I also have a swift3 branch. Also something on my long wish-list :)

Cheers.

**Comment by NilsLattek** [comment]
Sounds awesome! I will help with swift 3 as soon as it is out and my project won't compile any more 😄

**Comment by davidstump** [comment]
Awesome! Thanks again for being involved.

**Comment by danielrees18** [comment]
`.receive()` hooks have been added in 0.7.0. As a new feature, let me know if anyone has issues using them. See the wiki for usage guides
