### ISSUE TITLE
Handle phx_error

### ISSUE THREAD

**Issue by NilsLattek** [davidstump/SwiftPhoenixClient#52]
When a client is connected to a channel and for some reason the channel crashes then phoenix restarts the channel (supervisor) and sends a `phx_error` event to the client.
The client should then try to rejoin the channel or else it cannot send or receive further messages.
From the js source: https://github.com/phoenixframework/phoenix/blob/master/web/static/js/phoenix.js#L310-L313

**Comment by dsrees** [comment]
I do not believe this is an issue any longer. closing for now.
