### ISSUE TITLE
Swift 3 errors

### ISSUE THREAD

**Issue by JakePrasad** [davidstump/SwiftPhoenixClient#60]
Hi, 

I installed SwiftPhoenixClient using cocoapods on an empty project, but when I try to open the xcworkspace, Xcode8 says that I need to choose to convert the code to either Swift3 or Swift2.3

After choosing Swift3 and letting XCode convert the code, I ended up with >30 errors, about 20 of which were due to StarScream and about 10 of which were because of SwiftPhoenixClient.

Do I need to install StarScream manually (not via the SwiftPhoenixClient cocoapods dependency), since it appears to be the cause of the errors?

Thanks,
Jake
![xcode_errors](https://cloud.githubusercontent.com/assets/1834101/19412899/7e103d1c-92d4-11e6-9d94-407231f9d0e6.png)

**Comment by davidstump** [comment]
Cocoapods should install the most recent version of the client which is Swift3 compatible and pulls in the newest version of Starscream which is as well. Did you specify a SwiftPhoneixClient version in your Podfile?

**Comment by JakePrasad** [comment]
That's what I thought too, and I hadn't specified a version in the Podfile when I ran pod install.

I tried reinstalling cocoapods in case it was having trouble integrating with Xcode8 (it seems a few other people on Github have run into this issue).
The reinstallation seems to have fixed the errors and I can now build the project.
