### ISSUE TITLE
Join room without sending a message

### ISSUE THREAD

**Issue by axelson** [davidstump/SwiftPhoenixClient#62]
Is it possible to join a room without sending a message? We don't want to actually send a message when joining.

**Comment by davidstump** [comment]
Since you mentioned room, I will assume you are using the phoenix_chat_example? If so, the `user:entered` message is manually triggered on the channel itself:

https://github.com/chrismccord/phoenix_chat_example/blob/master/web/channels/room_channel.ex#L27-L31

Your code could do something different (or nothing) with that event and no message would be sent. Likewise, your Swift code would no longer need the `user:entered` block in your ViewController.

Hope that helps.

**Comment by axelson** [comment]
@davidstump I suppose instead of room I should say channel. I'm talking about the client sending a message to the server, not the server sending a message to the client.

The current syntax for joining a channel is:
```
socket.join(topic: "rooms:lobby", message: Message(subject: "status", body: "joining")) { channel in
  let channel = channel as! Channel
}
```

Is there any way to not send that initial message? And just do something like:

```
socket.join(topic: "rooms:lobby") { channel in
  let channel = channel as! Channel
}
```

**Comment by willc0de4food** [comment]
@axelson You could try modifying the code in your project to add some overload methods which don't include a message. For ex: in Pods -> Pods -> SwiftPhoenixClient -> Channel.swift add
`init(topic: String, callback: @escaping ((Any) -> Void), socket: Socket) {`
`        (self.topic, self.callback, self.socket) = (topic, { callback($0) }, socket)`
`    }`

Then in Pods -> Pods -> SwiftPhoenixClient -> Socket.swift add
`public func join(topic: String, callback: @escaping ((Any) -> Void)) {`
`        let chan = Channel(topic: topic, callback: callback, socket: self)`
`        channels.append(chan)`
`        if isConnected() {`
`            print("joining")`
`            rejoin(chan: chan)`
`        }`
`    }`

You don't need to replace the methods already in the code, the compiler will choose the appropriate method based on the params supplied. I'm not *positive* this will work, but you could give it a try.

**Comment by danielrees18** [comment]
API changes coming in the next release which will allow for optional payloads when sending a message (see #83)

Hopefully we'll get a new release out in a week or so after more testing. Thank you!
