### ISSUE TITLE
Auth token example for Swift library

### ISSUE THREAD

**Issue by mojidabckuu** [davidstump/SwiftPhoenixClient#65]
I've just finished reading great book "Programming Phoenix". The sample to create video annotation identifies a user through `window-token` which is part of DOM itself. What is the approach for the client library?. What is best approach I can apply to keep my channel specific for a user and safe.
Phoenix <3 !

**Comment by danielrees18** [comment]
@mojidabckuu when joining a channel, you can pass parameters which will be sent as a payload to the server. On the server side, you will need to verify the params sent are correct.

```Swift
socket.join(topic: "rooms:lobby", payload: ["auth_token": "Bearer abc123"]) { (channel) in }
```
