### ISSUE TITLE
Escape query parameters when connecting to socket endpoints

### ISSUE THREAD

**Issue by schrockwell** [davidstump/SwiftPhoenixClient#66]
I encountered an error trying to connect to a socket with a parameter that had a space in it. I dug into the `Socket` initializer and noticed that the query parameters are simply being appended do the endpoint URL without any proper escaping.

The `NSURLComponents` class can be utilized to take care of the proper URL formatting. See here: https://www.ralfebert.de/snippets/ios/encoding-nsurl-get-parameters/

**Comment by markshiz** [comment]
I encountered the same problem.

**Comment by danielrees18** [comment]
This should be resolved in #82 and will be available in the next release. Thanks!
