### ISSUE TITLE
Setup socket

### ISSUE THREAD

**Issue by sger** [davidstump/SwiftPhoenixClient#68]
Hello,

Is possible to initialize socket within viewDidLoad method it's important to pass some special parameters like token for example the scenario is user login get the token and after construct socket object in my example doesn't seems to work any ideas?

**Comment by danielrees18** [comment]
@sger You can initialize the socket with whatever parameters you need, such as a token. Then calling `open()` will open the socket to the server, passing the given parameters. 

For more, please see [the usage guide](https://github.com/davidstump/SwiftPhoenixClient/wiki/Usage-Guide#creating-a-socket).

Closing this as resolved. If you are still having trouble, please let me know
