### ISSUE TITLE
Handle error when sending data 

### ISSUE THREAD

**Issue by sushimatou** [davidstump/SwiftPhoenixClient#70]
I use Swift Phoenix Client in my app to sending & receive data with Phoenix sockets. If I use the traditional way with channel.on to receive data on events, I use also your specific way to send data with method socket.send. But I doesn't really understand how I can handle errors at this moment, in others words, how can I verifiy if the connection is always established, if my message was send correctly etc.

**Comment by ManueGE** [comment]
Any news on this?

**Comment by danielrees18** [comment]
@sushimatou @ManueGE 

We released [0.7.0-rc1](https://github.com/davidstump/SwiftPhoenixClient/releases/tag/0.7.0-rc1) today which adds callbacks when sending a message. You can test it out and see if it fits your needs. 

```
pod 'SwiftPhoenixClient', '0.7.0-rc1'
```

You can now receive events when sending a message. This is a new feature so please let me know if you guys have any trouble with it.

See [the wiki](https://github.com/davidstump/SwiftPhoenixClient/wiki/Usage-Guide#sending-messages) for more details on sending messages
