### ISSUE TITLE
How to disable console log..?

### ISSUE THREAD

**Issue by phanisai4u** [davidstump/SwiftPhoenixClient#71]
Hi, Thanks for the great framework.
how can I disable and enable console log for this frame work...?

```
{"topic":"phoenix","ref":"165","payload":{"status":"ok","response":{}},"join_ref":null,"event":"phx_reply"}
json: {"event":"heartbeat","topic":"phoenix","ref":"166","payload":{"body":"Pong"}}
socket message: {"topic":"phoenix","ref":"166","payload":{"status":"ok","response":{}},"join_ref":null,"event":"phx_reply"}
```

**Comment by davidstump** [comment]
There isn't at the moment, but I just added a Logger class so I can replace all of the `print` calls with `Logger.debug` that will use `#if DEBUG` to conditionally print the output only in debug mode. Thanks for mentioning.

**Comment by phanisai4u** [comment]
Thanks, @davidstump 👍
