### ISSUE TITLE
Not working with Swift 4

### ISSUE THREAD

**Issue by thiagodelmotte** [davidstump/SwiftPhoenixClient#72]
Do you guys have plans to update to Swift 4?

**Comment by davidstump** [comment]
I just pushed up some updates to the `master` branch a few days ago. It passes the Swift 4 converter on Xcode, but hasn't passed a real-world test yet. Would you have time to give it a try in your app/env?

Cheers!

**Comment by thiagodelmotte** [comment]
Hy David,

Thank you for the quickly response!

I've made some tests and it's fine with Swift 4, but I'm having other issues:

1) When using leave method, I'm getting this error:
Message.swift, Line 45
Could not cast value of type 'Swift.String' (0x103ef0f68) to 'Swift.Dictionary<Swift.String, Any>' (0x103f21f20).
2017-09-27 17:45:41.970208-0300 Lassie Development[2059:745874] Could not cast value of type 'Swift.String' (0x103ef0f68) to 'Swift.Dictionary<Swift.String, Any>' (0x103f21f20).

2) I'm not getting callbacks, return nothing:
chan.on(event: "join") {}
chan.on(event: "error") {}

Do you have time to fix these issues?

Thank you!

**Comment by danielrees18** [comment]
hey @thiagodelmotte 

We released [0.7.0-rc1](https://github.com/davidstump/SwiftPhoenixClient/releases/tag/0.7.0-rc1) today. You can test it out and see if you are still having problems. Hopefully we'll roll out the final version next week if all is 💯 

```
pod 'SwiftPhoenixClient', '0.7.0-rc1'
```

**Comment by thiagodelmotte** [comment]
HEy @danielrees18 I appreciate that! Thank you!

**Comment by danielrees18** [comment]
Closing this. Let me know if you have any more problems!
