### ISSUE TITLE
Token Authorization

### ISSUE THREAD

**Issue by aaa707** [davidstump/SwiftPhoenixClient#9]
Hi there,

Thank you for the awesome pod!

I'm building a chat app using this, but I want to check user authentication when socket joining.
It's related https://github.com/phoenixframework/phoenix/issues/699 .

Do you have a plan to pass not only Phoenix.Message but something?

Best,

**Comment by davidstump** [comment]
That's definitely something to look into. I will have to read up on the decisions from that Phoenix thread. 

Thanks for the suggestion!

**Comment by aaa707** [comment]
Hi @davidstump,

Thank you for your positive reply.
I'm looking forward to your update!
If I can help your work, I'll raise PR something.

Thanks,

**Comment by chrismccord** [comment]
This is pretty simple. Socket.connect needs to accept a dictionary and convert it to query string params to pass up with the websocket upgrade path. That's it!

**Comment by mudphone** [comment]
Just jotting down some notes here, regarding @chrismccord 's comments, and a brief discussion about it today.

The deps/phoenix/web/static/js/phoenix.js comments mention the use of the params passed in the JS client, in this style:

````javascript
//     let socket = new Socket("/ws", {params: {userToken: "123"}})
//     socket.connect()
````

Then it uses the `static serialize()` method to turn the params object into a query string. We should be able to do this in the SwiftPhoenixClient.

**Comment by davidstump** [comment]
Could you let me know if this got resolved with your PR?

**Comment by tony612** [comment]
@davidstump I think that PR is not enough. The params should be passed to server when the socket connection is built.
