### ISSUE TITLE
Non Working Usage Example

### ISSUE THREAD

**Issue by optikfluffel** [davidstump/SwiftPhoenixClient#92]
When trying this example, from the bottom of [the Channels and Events section in the Usage Guide](https://github.com/davidstump/SwiftPhoenixClient/wiki/Usage-Guide#channels-and-events):

```Swift
/// Called before the `.on(event:, callback:)` hook is called for all events. Allows you to
/// hook in an manipulate or spy on the incoming payload before it is sent out to it's
/// bound handler. You must return the payload, modified or unmodified
channel.onMessage { (event, payload, ref) -> Payload in 
    payload["modified"] = true
    return payload 
}
```

XCode tells me for the `payload["modified"] = true` part that it

> 🛑 Cannot assign through subscript: 'payload' is a 'let' constant

**Comment by dsrees** [comment]
Docs have been updated
