### ISSUE TITLE
No rejoin when loosing network connection

### ISSUE THREAD

**Issue by ALexanderLonsky** [davidstump/SwiftPhoenixClient#93]
Hello, 
I am using SwiftPhoenixClient in my Mac OS application.

I've just updated to 0.8.1, the previous version was 0.6.0.

0.8.1 does not rejoin.
My code:
`socket = Socket(url: "ws://...")
        
        socket.onOpen = { 
            print("onOpen")
        }
        socket.onClose = { 
            print("onClose")
        }
        socket.onError = { error in
            print("onError")
        }
        socket.connect()
        
        channel = self.socket?.channel("mychannel")                
        
        channel.onError {
            (payload) in print("Error: ", payload)
        }
        
       channel.onClose {
            (payload) in print("Channel Closed")            
        }
        
       channel.join().receive("ok") { (payload) in
            print("Channel Joined", payload)
            }.receive("error"){ (payload) in
                print("Failed to join", payload)
            }.receive("timeout") { (payload) in
                print("Networking issue...", payload)
        }`
So when I'm online it connects successfully, and prints "onOpen"->"Channel Joined"
Then I turn off my network and receive "onError".
Next step is to turn on it again - no actions. This method is not called:
`open func stream(_ aStream: Stream, handle eventCode: Stream.Event)`
But if I do the same for 0.6.0 - it works perfectly. 

I wouldn't like to use 0.6.0 because new APIs look much better.
Could you help me with this please?

**Comment by ALexanderLonsky** [comment]
Ok, I see that you removed reconnection Timer and it seems I need to handle it myself.

**Comment by dsrees** [comment]
@ALexanderLonsky Yes, the rejoin timer was removed due to the change of the structure of the socket. We can look to adding it back in or making it a flag that can be set, but for now it would be best to handle it on your own.

**Comment by dsrees** [comment]
@ALexanderLonsky this will be added back to the library in release `0.9.0` along with a way to configure your own logic for when the socket should reconnect. Should be able to release in the next week or so

**Comment by LucasVanDongen** [comment]
Why hasn't 0.9 been pushed to CocoaPods?

**Comment by dsrees** [comment]
@LucasVanDongen I was waiting to get some more testing done first before pushing out an official release. I am pretty comfortable with the release however so I'll work on rolling it out.

**Comment by dsrees** [comment]
0.9.0 is available now which includes a configurable rejoin timer. Wiki is being updated on usage
